# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'cx-granite'
    location: 'Southeast Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/vishnu-vashist/azure-rm-es-temp/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/vishnu-vashist/azure-rm-es-temp/main/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployTemplatePipe'
